/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_staticjni_StaticJni */

#ifndef _Included_com_example_staticjni_StaticJni
#define _Included_com_example_staticjni_StaticJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_staticjni_StaticJni
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_staticjni_StaticJni_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
